name: CI

on:
  push:
    branches: [ "yungpanz-patch-1" ]
  pull_request:
    branches: [ "yungpanz-patch-1" ]

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - run: bazel build //...
    # - run: bazel test //...
